---
title: "R Notebook"
output: html_notebook
---




download
```{r eval=FALSE, include=FALSE}
# install.packages("remotes")
remotes::install_github("colinfay/dockerfiler")
```


```{r}
library(dockerfiler)
```

https://mdneuzerling.com/post/user-getting-started-with-r-and-docker/
https://towardsdatascience.com/creating-sandbox-environments-for-r-with-docker-def54e3491a3

dockerfile
https://colinfay.me/docker-r-reproducibility/
https://pokyah.github.io/post/using-r-with-docker/

datatable
https://hub.docker.com/r/jangorecki/r-data.table/dockerfile

reticulate
# r installed in python container
https://stackoverflow.com/questions/54437030/how-can-i-create-a-docker-image-to-run-both-python-and-r

#built on r-ver which doesn't have rstudio
https://github.com/MangoTheCat/docker-buildr-reticulate/blob/master/Dockerfile
https://github.com/mikebirdgeneau/dockerfiles/blob/master/r-base-dev-ext/Dockerfile
https://github.com/ghislainv/docker-forestatrisk/blob/master/Dockerfile

h2o

not used
```{r eval=FALSE, include=FALSE}
pkg_list <- c(
  "pander",
  "rmarkdown",
  "knitr",
  "reticulate",
  "data.table",
  "ggplot2",
  "lubridate",
  "stringr",
  "scales",
  "janitor",
  "WVPlots",
  "vtreat",
  "h2o")

save(pkg_list,file="requirements.R")
```


```{r eval=FALSE, include=FALSE}
load("requirements.R")
```


from
```{r}
my_dock <- Dockerfile$new("rocker/rstudio:latest")
```

not run
```{r eval=FALSE, include=FALSE}
my_dock$MAINTAINER("David Lucey", "dnl2001@stern.nyu.edu")
```


not run
```{r eval=FALSE, include=FALSE}
# CRAN mirror
my_dock$ENV("CRAN_MIRROR","https://ftp.igh.cnrs.fr/pub/CRAN/")

# locale
my_dock$RUN("locale-gen en_US.UTF-8")
my_dock$ENV("LANG", "en_US.UTF-8")
my_dock$ENV("LANGUAGE","en_US:en")
my_dock$ENV("LC_ALL","en_US.UTF-8")
```

not run
```{r eval=FALSE, include=FALSE}
# Install debian packages with apt-get
# https://github.com/ghislainv/docker-forestatrisk/blob/master/Dockerfile

my_dock$ADD(from="apt-packages.txt", to="/tmp/apt-packages.txt")
my_dock$RUN("apt-get update --fix-missing \ && 
            apt-get upgrade -y \ &&
            pt-get dist-upgrade -y \ &&
            xargs -a /tmp/apt-packages.txt apt-get install -y")
```

not run
```{r eval=FALSE, include=FALSE}
# Clean-up after debian
my_dock$RUN("apt-get autoremove -y \ \n && apt-get clean -y")
```

if h2o needed
```{r eval=FALSE, include=FALSE}
https://gitlab.com/jangorecki/dockerfiles/blob/master/h2o/Dockerfile
# java

my_doc$RUN("apt-get update -qq \\
    && apt-get install -y openjdk-8-jdk \\
    && rm -rf /var/lib/apt/lists/*")

# h2o

my_dock$RUN"curl -O http://download.h2o.ai/versions/h2o-3.10.0.7.zip \\
    && unzip h2o-3.10.0.7.zip \\
    && mv h2o-3.10.0.7/h2o.jar")

my_dock$CMD("java -Xmx6g -jar h2o.jar -name dockerized-h2o")
```


```{r}
# install python3, virtualenv and anaconda

my_dock$RUN("apt-get install -y \
		python3-pip \
		python3-dev \
	&& pip3 install virtualenv")

# install anaconda

my_dock$RUN("echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda2-2019.10-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh")

my_dock$ENV("PATH", "opt/conda/bin:$PATH")
```



python
```{r eval=FALSE, include=FALSE}
# python
#my_dock$COPY("requirements.R","requirements.R")
my_dock$RUN("apt-get update")

my_dock$RUN(
    "apt-get install -y --no-install-recommends \\
		libgdal-dev \\
		libproj-dev \\
		python-pip \\
		python-setuptools \\
	  && apt-get clean \\ 
	  && rm -rf /var/lib/apt/lists/*"
		)

```


run pkg_list
```{r eval=FALSE, include=FALSE}
# R packages (including reticulate)

my_dock$RUN('source("requirements.R"); install.packages(pkg_list,repos="https://cran.rstudio.com/")')
```

rocker/tidyverse image for R-packages
```{r}
my_dock$RUN(
  "apt-get update -qq && apt-get -y --no-install-recommends install \\
  libxml2-dev \\
  libcairo2-dev \\
  libsqlite-dev \\
  libmariadbd-dev \\
  libmariadbclient-dev \\
  libpq-dev \\
  libssh2-1-dev \\
  && install2.r --error \\
    --deps TRUE \\
    pander \\
    rmarkdown \\
    knitr \\
    reticulate \\
    data.table \\
    ggplot2 \\
    lubridate \\
    stringr \\
    janitor \\
    h2o \\ 
    devtools \\
    formatR \\
    remotes"
  )
  
```



```{r eval=FALSE, include=FALSE}
my_dock$CMD('["/init"]')
```


```{r}
class(my_dock)
```

```{r}
class(my_dock$Dockerfile)
```

